### ISSUE TITLE
测试修改过host以后还是锁100kb/s

### ISSUE THREAD

**Issue by ZhxChen** [wmltogether/XboxSpeedTest#1]
测试修改过host以后还是锁100kb/s，能看到xbox已经和host的ip进行通信了。是巨硬又搞什么骚操作了吗？

**Comment by wmltogether** [comment]
用的dnsmasq还是smartdns？

**Comment by ZhxChen** [comment]
我的smartdns在dnsmasq上游，修改的DNSmasq。

**Comment by wmltogether** [comment]
试一下把cn域名也劫持到自定义的ip上，因为不确定游戏到底会走哪个cdn，但是一共就这6个域名

**Comment by ZhxChen** [comment]
是的，我查看了一下dnsmasq的解析记录。明明.com的已经有IP了，为什么会跳转到cn。是xbox找assets1.xboxlive.com的host定义服务器通讯，服务器说你去找cn吧。是这样么？

**Comment by ZhxChen** [comment]
还有好奇你们的CDN iplist是怎么来的？能透露一下吗？

**Comment by wmltogether** [comment]
解析用哪个host据说和xbox的语言有关系，简体中文+大陆默认会优先查.cn域名的样子，.cn查询资源没有自己会fallback到.com的ip，但是.cn一部分资源返回的ip不正确导致了锁死100k。
cdn list直接去ping.chinaz.com国际测速扫一遍ip就行了，不能用国内哦

**Comment by ZhxChen** [comment]
> 解析用哪个host据说和xbox的语言有关系，简体中文+大陆默认会优先查.cn域名的样子，.cn查询资源没有自己会fallback到.com的ip，但是.cn一部分资源返回的ip不正确导致了锁死100k。
> cdn list直接去ping.chinaz.com国际测速扫一遍ip就行了，不能用国内哦

我是设置美区简字，多谢解答
