### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by isilcala** [wmltogether/XboxSpeedTest#2]
Hi，

因为没有看到 releases, 直接 clone 下来以后运行 python XboxSpeedTest.py，报了很多错，用了一个 mac 一个 centos 结果一样。对 Python 语法不太熟悉没找到问题。请看下是否 clone 下来的漏了什么文件？谢谢。

***************  Xbox CDN SpeedTest *****************
** Finding your best CDN for Xbox Game Downloads ****
[TEST 1/68] [Address: 23.12.40.184][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 2/68] [Address: 219.76.10.33][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 3/68] [Address: 203.69.138.26][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 4/68] [Address: 104.114.76.35][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 5/68] [Address: 42.56.76.121][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 6/68] [Address: 65.152.2.123][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 7/68] [Address: 67.24.197.254][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 8/68] [Address: 2.23.97.201][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 9/68] [Address: 8.248.113.254][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 10/68] [Address: 8.248.115.254][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 11/68] [Address: 104.102.249.72][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 12/68] [Address: 219.76.10.193][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 13/68] [Address: 23.223.198.179][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 14/68] [Address: 58.216.96.60][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 15/68] [Address: 8.247.210.126][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 16/68] [Address: 92.122.244.56][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 17/68] [Address: 67.24.191.254][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 18/68] [Address: 123.125.110.199][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 19/68] [Address: 72.247.211.225][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 20/68] [Address: 8.238.30.126][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 21/68] [Address: 23.46.210.209][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 22/68] [Address: 23.12.40.144][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 23/68] [Address: 184.28.218.49][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 24/68] [Address: 23.46.229.16][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 25/68] [Address: 8.238.35.126][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 26/68] [Address: 23.50.49.179][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 27/68] [Address: 72.21.81.200][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 28/68] [Address: 23.53.228.33][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 29/68] [Address: 23.45.51.192][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 30/68] [Address: 65.152.2.152][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 31/68] [Address: 104.114.76.178][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 32/68] [Address: 23.55.47.165][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 33/68] [Address: 139.175.236.223][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 34/68] [Address: 72.247.211.201][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 35/68] [Address: 2.23.97.17][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 36/68] [Address: 8.248.91.254][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 37/68] [Address: 104.86.183.17][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 38/68] [Address: 23.205.220.122][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 39/68] [Address: 104.114.77.51][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 40/68] [Address: 23.48.201.17][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 41/68] [Address: 23.32.241.147][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 42/68] [Address: 184.25.56.92][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 43/68] [Address: 104.114.77.17][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 44/68] [Address: 219.76.10.184][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 45/68] [Address: 23.46.229.26][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 46/68] [Address: 219.76.10.202][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 47/68] [Address: 23.200.75.20][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 48/68] [Address: 23.223.198.161][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 49/68] [Address: 8.241.23.126][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 50/68] [Address: 8.248.3.254][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 51/68] [Address: 117.18.232.200][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 52/68] [Address: 23.45.51.136][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 53/68] [Address: 184.150.154.49][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 54/68] [Address: 23.67.57.217][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 55/68] [Address: 23.2.16.32][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 56/68] [Address: 8.240.27.254][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 57/68] [Address: 58.216.106.252][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 58/68] [Address: 172.232.10.192][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 59/68] [Address: 152.199.19.161][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 60/68] [Address: 104.114.76.145][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 61/68] [Address: 67.24.185.254][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 62/68] [Address: 104.124.62.49][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 63/68] [Address: 23.46.210.208][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 64/68] [Address: 8.255.130.254][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 65/68] [Address: 173.205.28.154][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 66/68] [Address: 8.238.41.126][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 67/68] [Address: 205.185.216.19][Errno 2] No such file or directory
 ....... 0.0KB/s 
[TEST 68/68] [Address: 184.28.50.145][Errno 2] No such file or directory
 ....... 0.0KB/s 
[LOG]All CDN Test complete. Have fun!
[LOG]All CDN Failed, Bye Bye!

[Done] exited with code=0 in 0.372 seconds

**Comment by wmltogether** [comment]
linux系统需要做如下修改（*其实跟python没关系，是系统的curl路径不同，win10根本没有curl，所以我自己在./bin下放了一个）
所以:
先确认python的版本，python -V, 这个脚本是2.7写的
把脚本的CURL_PATH= "bin/curl" 改成 "curl",  你如果不知道curl在哪里，就终端输入一下where curl看看在哪
顺便linux系统下面，subprocess.Popen里面的shell=False要改成shell=True

**Comment by isilcala** [comment]
之前改了 curl 路径，倒是不知道还有个 shell=True 要改。现在好了。谢谢。建议也把这个 tips 放进 README 里哈。
