### ISSUE TITLE
无法使用，报错

### ISSUE THREAD

**Issue by tanglueyi** [wmltogether/XboxSpeedTest#4]
![image](https://user-images.githubusercontent.com/3315564/111284376-0650f380-867b-11eb-806e-4aaac6ae500e.png)

**Comment by wmltogether** [comment]
curl路径问题，自己把curl路径改一下吧
[参见issue:2](https://github.com/wmltogether/XboxSpeedTest/issues/2)
查询当前系统的curl位置：where curl
顺便linux系统下面，subprocess.Popen里面的shell=False要改成shell=True

**Comment by tanglueyi** [comment]
> curl 路径问题，自己把 curl 路径改一下吧
> [参见 issue:2](https://github.com/wmltogether/XboxSpeedTest/issues/2)
> 查询当前系统的 curl 位置：where curl
> 顺便 linux 系统下面，subprocess.Popen 里面的 shell=False 要改成 shell=True

已修复，感谢，另外请问如果当前电脑挂了梯子（Surge for Mac）并且打开了增强模式会影响测速结果吗？

**Comment by wmltogether** [comment]
增强模式会全局代理终端影响结果，要提前关掉

**Comment by tanglueyi** [comment]
> 增强模式会全局代理终端影响结果，要提前关掉

您也用Surge做网关吗？请问您测速完是怎么配置的？
目前我的配置如下：
```
[Host]
# Xbox Download
assets1.xboxlive.com = 23.2.16.32
assets2.xboxlive.com = 23.2.16.32
dlassets.xboxlive.com = 23.2.16.32
assets1.xboxlive.cn = 23.2.16.32
assets2.xboxlive.cn = 23.2.16.32
dlassets.xboxlive.cn = 23.2.16.32
```
不知道是否正确？

**Comment by wmltogether** [comment]
没，我是直接写路由器里了做本地dns了，xbox直接解析本地dns，不想在pc上绕一圈

**Comment by tanglueyi** [comment]
> 没，我是直接写路由器里了做本地 dns 了，xbox 直接解析本地 dns，不想在 pc 上绕一圈

了解，感谢
